# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvseries',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='flags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
