# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_auto_20171109_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseries',
            name='numberofseasons',
            field=models.IntegerField(default=0),
        ),
    ]
