# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0006_auto_20171113_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasons',
            name='ylink',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
