# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeseries',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
