# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_animeseries_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeseries',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animeseries',
            name='flags',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
