# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_auto_20171109_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeseries',
            name='numberofarcs',
            field=models.IntegerField(default=0),
        ),
    ]
