# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0004_auto_20171109_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeseries',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animeseries',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
