# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_auto_20171112_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeseries',
            name='link',
        ),
    ]
