# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_auto_20171113_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcs',
            name='ylink',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
